### ISSUE TITLE
Message validation

### ISSUE THREAD

**Issue by RKushnir** [mailboxer/mailboxer#48]
Hi,
currently when you use `send_message` there's no way to get the list of errors if it fails. I would like to tell user that he forgot to specify the recipient, for example. Maybe, it's better to split this function to allow the following:

    @message = user.compose_message(params)
    if @message.deliver
      redirect_to :sentbox
    else
      render :new
    end

**Comment by dstosik** [comment]
Hello,
It seems I'm pulling this issue from the limbo, but I'm facing the same problems...

I want to validate a message in order to avoid invalid record errors. Updating to 0.13.0 allowed me to check the `Receipt` object returned by `#send_message`. I can even use `receipt.errors` to display the error messages in my new message form, as suggested by @Roendal above, but the messages are not "perfect", as they say stuff like "**Notification** subject can't be blank". I'd rather have those messages say "**Message** subject can't be blank".
Also, as I'm using `#form_tag` to build the form markup, it gets difficult to highlight erroring fields.

Is my best solution to use `#form_for` on a stub `Message` object that I'll use only for error handling?

Any other suggestion?

**Comment by deivid-rodriguez** [comment]
This is now handled differently than before. I'd close this and handle any issues that come up with the behavior separately.
